### ISSUE TITLE
can you help me? 

### ISSUE THREAD

**Issue by ghost** [MasterEric/OpenFLWindowTest#1]
so i used kades extenshion-webm and i got an error when i tryed to build fnf test  

 obj\msvc1964-nc\7f39cded_Stage.obj : fatal error LNK1136: invalid or corrupt file  

thats the error and i have git and stuff

**Comment by ghost** [comment]
and im on a windows 11 Lenovo computer

**Comment by EliteMasterEric** [comment]
Try the following steps:

1. Uninstall Haxe.
2. Install the LATEST version of Haxe (currently 4.2.4). Previous advice was to install 4.1.5 but that's outdated info.
3. Follow the full list of troubleshooting steps [here](https://github.com/KadeDev/Kade-Engine/blob/master/docs/building.md#dependencies)

**Comment by ghost** [comment]
ok thank you also if you want can you please add me on discord mine is Jonnycat#8275

**Comment by ghost** [comment]
i just love your work
