### ISSUE TITLE
can you help  me on my extenshion-webm error

### ISSUE THREAD

**Issue by ghost** [MasterEric/OpenFLWindowTest#2]
when i was building it i get this error  

./common/ExternalInterface.cpp(851): warning C4477: 'printf' : format string '%ld' requires an argument of type 'long', but variadic argument 2 has type 'size_t'
./common/ExternalInterface.cpp(851): note: consider using '%zd' in the format string  

so i was wondering if you can fix this?

**Comment by EliteMasterEric** [comment]
Does it build successfully? `warning` indicates an issue that can often be ignored without issue.

Can you try deleting your `export` folder and building again?

If it fails again, please post the FULL log.

**Comment by ghost** [comment]
ok
